# Generated by Django 3.2.14 on 2022-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlInput', '0003_auto_20220707_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_status_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
