# Generated by Django 3.2.14 on 2022-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlInput', '0004_link_link_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_text',
            field=models.CharField(default='https://', max_length=200),
        ),
    ]
