# Generated by Django 3.2.14 on 2022-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlInput', '0005_alter_link_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_text',
            field=models.URLField(),
        ),
    ]
