# Generated by Django 3.2.14 on 2022-07-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlInput', '0007_alter_link_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_status_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='link',
            table='link',
        ),
    ]
