# Generated by Django 3.2.14 on 2022-07-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlInput', '0008_auto_20220711_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_status_code',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
